### ISSUE TITLE
dsn parameter throws error

### ISSUE THREAD

**Issue by nhsbsa-kaygo** [nhsbsa-data-analytics/nhsbsaR#28]
@mgarbuzov, dsn parameter throws error: "Error: nanodbc/nanodbc.cpp:1021: IM002: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified "

Can you please look into this? At the moment, con_nhsbsa function doesn't work.

**Comment by nhsbsa-garbu-m** [comment]
@kygoffe did you get around this?

If not, please refer to my Teams post in DALL & Stats from 21-Feb-22 (can't link it here).

As you know we have a couple of dozen Azure VDs, and I can only assume the settings failed to filter down to one/few of them. If you are unlucky enough to find yourself on one of those AVDs, either log-off and -on until you get a good one, or use: `con_nhsbsa(database = "DALP", dsn = NULL)` which will use the connection at slower speed we had before.

Platform Services are working to deliver bespoke DALL AVDs to us imminently, which should all be configured correctly.
