### ISSUE TITLE
Running the app gives error Warning: Error in loadNamespace: there is no package called ‘nhsrtheme’ in the chart

### ISSUE THREAD

**Issue by nhsbsa-mamcp** [nhsbsa-data-analytics/nhsbsaR#7]
I searched for references to {nhsrtheme}, and found only these 2. Does {nhsrtheme} need added to the imports or depends perhaps?

EDIT: I see that having {nhsrtheme} specified in the remotes is supposed to handle importing it. So I am not sure what is causing the error after all.

![image](https://user-images.githubusercontent.com/91202154/139597191-fa2e1dad-f0b5-471b-a903-f2bf7744758f.png)

**Comment by ghost** [comment]
Not sure how to get around this one other than `devtools::install_github("nhs-r-community/nhsrtheme")`... if you can figure it out please create a PR as it's a bit frustrating!!

It is used in the package to grab the hex codes for the colours defined in the NHS identity

**Comment by nhsbsa-mamcp** [comment]
I think I have just about figured this issue out. Firstly, can use {drat} to create a private repo with the zipped packages in it. Then using the additional_repositories option in DESCRIPTION file you just give the URL for that drat repo.

For actually making sure any non-CRAN dependencies are pulled in when deploying to shinyapps.io, you HAVE to do the devtools::install_github()– turns out rsconnect works out how to get non-CRAN packages by how you install them locally. But it does not recognise when drat has been used!

I got it all working last night, so will have a look into a PR 😊


[Description: NHSBSA Email signature (V1) 08]
Stella House, Goldcrest Way, Newburn Riverside, Newcastle upon Tyne, NE15 8NY
Please read our email disclaimer online at: http://www.nhsbsa.nhs.uk/email.
To reduce our environmental footprint, please only print when necessary.

**Comment by ghost** [comment]
Think I have found maybe a simpler solution? I think that the package needs specifying in `Imports` as well as `Remotes`... let me check now 

https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

This is a common theme with other packages / apps in development using `{nhsbsaR}` so hope this is the solution!

**Comment by ghost** [comment]
Try this @MarkMc1089 

` remove.packages("nhsbsaR")`
`remove.packages("nhsrtheme")`
`detach("package:nhsbsaR", unload = TRUE)`
`detach("package:nhsrtheme", unload = TRUE)`
`devtools::install_github(repo = "nhsbsa-data-analytics/nhsbsaR", ref = "7-fix-non-cran-dependency-issue")`

**Comment by nhsbsa-mamcp** [comment]
Unfortunately didn't work:

```
> remove.packages("nhsbsaR")
Removing package from ‘C:/Users/Mark/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
> remove.packages("nhsrtheme")
Removing package from ‘C:/Users/Mark/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
> detach("package:nhsbsaR", unload = TRUE)
Error in detach("package:nhsbsaR", unload = TRUE) : 
  invalid 'name' argument
> detach("package:nhsrtheme", unload = TRUE)
Error in detach("package:nhsrtheme", unload = TRUE) : 
  invalid 'name' argument
> devtools::install_github(repo = "nhsbsa-data-analytics/nhsbsaR", ref = "7-fix-non-cran-dependency-issue")
Downloading GitHub repo nhsbsa-data-analytics/nhsbsaR@7-fix-non-cran-dependency-issue
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: cpp11 (0.4.0 -> 0.4.1 ) [CRAN]
5: cli   (3.0.1 -> 3.1.0 ) [CRAN]
6: broom (0.7.9 -> 0.7.10) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
√  checking for file 'C:\Users\Mark\AppData\Local\Temp\RtmpeodwNO\remotes2ab462f21dc3\nhsbsa-data-analytics-nhsbsaR-56ab594/DESCRIPTION' ... 
-  preparing 'nhsbsaR':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'nhsbsaR_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/Mark/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
ERROR: dependency 'nhsrtheme' is not available for package 'nhsbsaR'
* removing 'C:/Users/Mark/Documents/R/win-library/4.1/nhsbsaR'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Mark/AppData/Local/Temp/RtmpeodwNO/file2ab42a5d2911/nhsbsaR_0.0.0.9000.tar.gz’ had non-zero exit status
```
